name: Embedded Software Factory

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ğŸ—ï¸ Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio

      - name: ğŸš€ Install PlatformIO
        run: pip install -U platformio

      - name: ğŸ› ï¸ Build Firmware
        # On dÃ©finit la variable PIO_BUILD_DIR ici pour l'usine
        run: pio run
        env:
          PIO_BUILD_DIR: ${{ github.workspace }}/.pio/build

      - name: ğŸ” Static Analysis (Quality Gate)
        run: pio check --fail-on-defect high
        env:
          PIO_BUILD_DIR: ${{ github.workspace }}/.pio/build

      - name: ğŸ“¦ Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32
          # On pointe vers le bon chemin de sortie
          path: .pio/build/esp32dev/firmware.bin